### ISSUE TITLE
[Enhancement] Compress backup folder into a single archive

### ISSUE THREAD

**Issue by av-romann** [egelliott3/MinecraftBdsManager#24]
At the moment, the scheduled backups are straight file/folder copies. It would be nice for the backup set to use an archive for like tar, zip, 7zip or similar to create a single file for easier backup management. 

Benefits:
- Smaller file size (actual benefit will vary based on world characteristics, with flat/homogenous worlds, likely more compressible)
- Atomic backup file for easier transfer off-system.

Drawback: 
- more processing and CPU time needed on backups (actual amount of extra time depends on compression method, but otherwise it's pretty linear by world size on disk and disk performance)
- Requires an extra processing step in any future features using the backup data (e.g. backup restoration)

**Comment by egelliott3** [comment]
Yup.  Great idea.  Didn't even think of it for whatever reason, but easy to add.

**Comment by egelliott3** [comment]
Added in 1.4.0 release
